#Part 1

In [5]:
import numpy as np
import pandas as pd
import io

In [6]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')
#taking in the dataset

In [7]:
df.head(5)
#displaying the initial 5 rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [8]:
df.tail(10)
#displaying the last 10 rows

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [9]:
df.max()
#finding the maximum of each column

longitude               -114.3100
latitude                  41.9500
housing_median_age        52.0000
total_rooms            37937.0000
total_bedrooms          6445.0000
population             35682.0000
households              6082.0000
median_income             15.0001
median_house_value    500001.0000
dtype: float64

In [10]:
df.min()

longitude              -124.3500
latitude                 32.5400
housing_median_age        1.0000
total_rooms               2.0000
total_bedrooms            1.0000
population                3.0000
households                1.0000
median_income             0.4999
median_house_value    14999.0000
dtype: float64

In [11]:
df.mean()
#finding the mean of each column

longitude               -119.562108
latitude                  35.625225
housing_median_age        28.589353
total_rooms             2643.664412
total_bedrooms           539.410824
population              1429.573941
households               501.221941
median_income              3.883578
median_house_value    207300.912353
dtype: float64

In [12]:
df.median()
#finding the median of each column

longitude               -118.4900
latitude                  34.2500
housing_median_age        29.0000
total_rooms             2127.0000
total_bedrooms           434.0000
population              1167.0000
households               409.0000
median_income              3.5446
median_house_value    180400.0000
dtype: float64

In [13]:
df.std()
#finding the standard deviation of each column

longitude                  2.005166
latitude                   2.137340
housing_median_age        12.586937
total_rooms             2179.947071
total_bedrooms           421.499452
population              1147.852959
households               384.520841
median_income              1.908157
median_house_value    115983.764387
dtype: float64

In [14]:
unique_val = df['total_bedrooms'].unique()
print(f"{unique_val}")

print(df['total_bedrooms'].nunique())
#finding the unique values in the column 'total_bedroooms'

[1283. 1901.  174. ... 1637. 1308.  936.]
1848


In [15]:
df['total_bedrooms_per_total_rooms']=df['total_bedrooms']/df['total_rooms']
print(df)
#creating a new column 'total_bedrooms_per_total_rooms' to df

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  media

In [16]:
df['total_bedrooms_per_total_rooms'].mean()
#finding the mean of the new column

0.21275998821034803

In [17]:
df['total_bedrooms_per_total_rooms'].std()
#finding the standard deviation of the new column

0.057823008903161756

In [18]:
df[df['median_income']>5]
#filtering to get the rows for which median_income is greater than 5

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [19]:
df[(df['total_rooms']>10000) & (df['median_house_value']<150000)]
#filtering to get the rows for which total_rooms is greater than 10000 and median_house_value lesser than 150000

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [20]:
df.to_csv('new.csv')
#saving the new df to a new file named 'new.csv

#Part 2

In [21]:
import numpy as np

In [22]:
a=np.arange(1, 21)
print(a)
#creating an array of integers from 1 to 20

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [23]:
a[1:20:2]
#splicing to get the even elements

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
b=np.random.randint(10,100,size=(5,4))
print(b)
#creating a 2D array of 5x4 dimensions with random integers between 10 and 100

[[36 10 43 95]
 [62 19 18 38]
 [68 89 42 23]
 [28 54 27 51]
 [70 56 73 89]]


In [25]:
b[0:3, 0:2]
# gettting a 3x2 subarray of the 2D array b

array([[36, 10],
       [62, 19],
       [68, 89]])

In [26]:
a.reshape(4, 5)
#reshaping a to a 4x5 2D array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
a.flatten()
print(a)
#flattening a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [28]:
c=np.random.randint(10,100,size=(4, 7))
print(b)
print(c)
np.matmul(b, c)
#matrix multiplication

[[36 10 43 95]
 [62 19 18 38]
 [68 89 42 23]
 [28 54 27 51]
 [70 56 73 89]]
[[63 93 74 57 43 33 13]
 [40 79 68 93 96 56 37]
 [64 59 90 44 72 77 38]
 [79 38 16 80 80 55 49]]


array([[12925, 10285,  8734, 12474, 13204, 10284,  7127],
       [ 8820,  9773,  8108,  9133,  8826,  6586,  4055],
       [12349, 16707, 15232, 15841, 16332, 11727,  6900],
       [ 9681, 10401,  8990, 11886, 12412,  8832,  5887],
       [18353, 18623, 16982, 19530, 20762, 15962, 10117]])

In [29]:
d=np.random.randint(0, 100, size=50)
#creating an array of length 50 with random integers between 0 and 100

In [30]:
d[d>50]
#filtering to get the elements greater than 50 using boolean indexing

array([65, 79, 56, 52, 64, 64, 91, 86, 57, 66, 65, 71, 90, 61, 59, 57, 82,
       72, 58, 91, 59, 82, 54, 57])

In [31]:
indices=[1, 5, 13, 15, 47, 49]
print(d[indices])
#using fancy indexing

[65 56 91 57 40 57]


In [32]:
print(np.mean(b, axis=0))
print(np.max(b, axis=0))
print(np.sum(b, axis=0))
#printing the mean, max and sum of each column of b

[52.8 45.6 40.6 59.2]
[70 89 73 95]
[264 228 203 296]


In [33]:
b[b>np.mean(b, axis=0)]
#filtering to get the elements in b which are greater than their respective column sum

array([43, 95, 62, 68, 89, 42, 54, 70, 56, 73, 89])

#Part 3

In [30]:
i=1
ans=1
while i<=100:
  ans=ans*i
  print(ans, "\n")
  i=i+1

#using a while loop to print fibonacci numbers from 1 to 100

1 

2 

6 

24 

120 

720 

5040 

40320 

362880 

3628800 

39916800 

479001600 

6227020800 

87178291200 

1307674368000 

20922789888000 

355687428096000 

6402373705728000 

121645100408832000 

2432902008176640000 

51090942171709440000 

1124000727777607680000 

25852016738884976640000 

620448401733239439360000 

15511210043330985984000000 

403291461126605635584000000 

10888869450418352160768000000 

304888344611713860501504000000 

8841761993739701954543616000000 

265252859812191058636308480000000 

8222838654177922817725562880000000 

263130836933693530167218012160000000 

8683317618811886495518194401280000000 

295232799039604140847618609643520000000 

10333147966386144929666651337523200000000 

371993326789901217467999448150835200000000 

13763753091226345046315979581580902400000000 

523022617466601111760007224100074291200000000 

20397882081197443358640281739902897356800000000 

815915283247897734345611269596115894272000000000 

334525266131638071081700620534407516

In [31]:
i=1
while i<=50:
  if i%3==0 and i%5!=0:
    print("Fizz")
  elif i%5==0 and i%3!=0:
    print("Buzz")
  elif i%3==0 and i%5==0:
    print("FizzBuzz")
  else:
    print(i)
  i=i+1


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [72]:
a=list(map(int,input().split()))
a.sort()
if len(a)%2==0:
  print((a[int(len(a)/2)]+a[int(len(a)/2-1)])/2)
else:
  print(a[int((len(a)-1)/2)])

#finding the median of a given list of numbers

1 3 2 5
2.5


In [11]:
a=list(map(int,input().split()))
sum=0
n=0
for x in a:
  sum+=x
  n=n+1
print(sum/n)

#finding the mean of a given list of numbers

1 2 3 4 5
3.0


In [13]:
a, b=map(int,input().split())
if b==0:
  print("Cannot divide by 0")
else:
  print(a/b)

#handling the case of division by 0 separately

2 0
Cannot divide by 0


#Part 4

In [2]:
import numpy as np
bonus=np.random.randint(0, 100, size=(3, 6, 7))
print(bonus)
#creating 3D array

[[[82  7 92 48 79 60 22]
  [46 51 42 13 96 22 34]
  [ 4 92  9 39 32 34 53]
  [75  4  2 92 24 99 40]
  [21  2 35 11 56 84 74]
  [68 34 27 27  2 57 84]]

 [[30 99 47 82 44 15 94]
  [83 87  6 78 65 62 24]
  [53 97 40 53 11 49 29]
  [ 6 49  4 20 19 56 76]
  [80 21 12 19 35  5 38]
  [37 97 71 80  6 68 92]]

 [[ 0 39 83 34 51 16 13]
  [37 33 29 31  1 23 47]
  [42 26 77 41 21 49 93]
  [20 40 51 55 92 24 45]
  [50 54 66 39  5 36 32]
  [95 65  5 46 96  0 55]]]


In [4]:
bonus.transpose(1, 0, 2)
#swaping 2 of its axis

array([[[52, 27, 31, 20, 43, 95, 34],
        [35, 40, 25, 20, 38, 18, 56],
        [99,  2, 67, 28, 57, 59, 96]],

       [[79, 93, 55, 82, 29,  2, 92],
        [81, 45, 90, 17, 66,  8, 18],
        [51, 75, 81, 48, 60, 36, 27]],

       [[31, 12, 44, 30, 49,  0, 36],
        [71,  5,  0, 29, 84, 28, 11],
        [75, 92, 99, 59, 25, 49, 17]],

       [[45, 78, 63, 43, 78, 51, 39],
        [94, 39, 49, 43, 10, 63, 90],
        [30, 90, 22, 67, 25, 58, 26]],

       [[73, 51, 82, 43, 16, 71, 15],
        [68, 28,  4, 68,  0, 71, 33],
        [ 8, 66, 23, 37, 63, 42, 17]],

       [[56, 37, 44,  4,  7, 53, 70],
        [19, 33, 69, 70, 61, 16, 62],
        [53, 61, 38,  4, 84,  4, 36]]])

In [3]:
print(np.sum(bonus, axis=0), "\n")
print(np.sum(bonus, axis=1), "\n")
print(np.sum(bonus, axis=2), "\n")
#printing sum of each axis

[[112 145 222 164 174  91 129]
 [166 171  77 122 162 107 105]
 [ 99 215 126 133  64 132 175]
 [101  93  57 167 135 179 161]
 [151  77 113  69  96 125 144]
 [200 196 103 153 104 125 231]] 

[[296 190 207 230 289 356 307]
 [289 450 180 332 180 255 353]
 [244 257 311 246 266 148 285]] 

[[390 304 263 336 283 299]
 [411 405 332 230 210 451]
 [236 201 349 327 282 362]] 



In [4]:
bonus2=np.random.randint(0, 100, size=(3,5))
a1=np.random.randint(0, 100, size=5)
print(bonus2, "\n")
print(a1, "\n")
h=bonus2+a1
print(h)
#adding a vector to each row of a 2D array

[[ 4 17 44 77 49]
 [88 71 21 15 77]
 [ 1 61 60 38 93]] 

[50 12 78 49 83] 

[[ 54  29 122 126 132]
 [138  83  99  64 160]
 [ 51  73 138  87 176]]
